export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST' as const;
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS' as const;
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE' as const;
export const ACTIVATE_USER_REQUEST = 'ACTIVATE_USER_REQUEST' as const;
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS' as const;
export const ACTIVATE_USER_FAILURE = 'ACTIVATE_USER_FAILURE' as const;
export const DEACTIVATE_USER_REQUEST = 'DEACTIVATE_USER_REQUEST' as const;
export const DEACTIVATE_USER_SUCCESS = 'DEACTIVATE_USER_SUCCESS' as const;
export const DEACTIVATE_USER_FAILURE = 'DEACTIVATE_USER_FAILURE' as const;
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST' as const;
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS' as const;
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE' as const;
export const PROMOTE_USER_TO_ADMIN_REQUEST = 'PROMOTE_USER_TO_ADMIN_REQUEST' as const;
export const PROMOTE_USER_TO_ADMIN_SUCCESS = 'PROMOTE_USER_TO_ADMIN_SUCCESS' as const;
export const PROMOTE_USER_TO_ADMIN_FAILURE = 'PROMOTE_USER_TO_ADMIN_FAILURE' as const;
export const REVOKE_USER_ADMIN_RIGHT_REQUEST = 'REVOKE_USER_ADMIN_RIGHT_REQUEST' as const;
export const REVOKE_USER_ADMIN_RIGHT_SUCCESS = 'REVOKE_USER_ADMIN_RIGHT_SUCCESS' as const;
export const REVOKE_USER_ADMIN_RIGHT_FAILURE = 'REVOKE_USER_ADMIN_RIGHT_FAILURE' as const;
export const PROMOTE_USER_TO_SPEAKER_REQUEST = 'PROMOTE_USER_TO_SPEAKER_REQUEST' as const;
export const PROMOTE_USER_TO_SPEAKER_SUCCESS = 'PROMOTE_USER_TO_SPEAKER_SUCCESS' as const;
export const PROMOTE_USER_TO_SPEAKER_FAILURE = 'PROMOTE_USER_TO_SPEAKER_FAILURE' as const;
export const VALIDATE_SPEAKER_REQUEST = 'VALIDATE_SPEAKER_REQUEST' as const;
export const VALIDATE_SPEAKER_SUCCESS = 'VALIDATE_SPEAKER_SUCCESS' as const;
export const VALIDATE_SPEAKER_FAILURE = 'VALIDATE_SPEAKER_FAILURE' as const;

export const SET_USER_SEARCH_FILTER = 'SET_USER_SEARCH_FILTER' as const;
export const SET_USER_ROLE_FILTER = 'SET_USER_ROLE_FILTER' as const;

export type UsersActionType =
    | typeof FETCH_USERS_REQUEST
    | typeof FETCH_USERS_SUCCESS
    | typeof FETCH_USERS_FAILURE
    | typeof ACTIVATE_USER_REQUEST
    | typeof ACTIVATE_USER_SUCCESS
    | typeof ACTIVATE_USER_FAILURE
    | typeof DEACTIVATE_USER_REQUEST
    | typeof DEACTIVATE_USER_SUCCESS
    | typeof DEACTIVATE_USER_FAILURE
    | typeof DELETE_USER_REQUEST
    | typeof DELETE_USER_SUCCESS
    | typeof DELETE_USER_FAILURE
    | typeof PROMOTE_USER_TO_ADMIN_REQUEST
    | typeof PROMOTE_USER_TO_ADMIN_SUCCESS
    | typeof PROMOTE_USER_TO_ADMIN_FAILURE
    | typeof REVOKE_USER_ADMIN_RIGHT_REQUEST
    | typeof REVOKE_USER_ADMIN_RIGHT_SUCCESS
    | typeof REVOKE_USER_ADMIN_RIGHT_FAILURE
    | typeof PROMOTE_USER_TO_SPEAKER_REQUEST
    | typeof PROMOTE_USER_TO_SPEAKER_SUCCESS
    | typeof PROMOTE_USER_TO_SPEAKER_FAILURE
    | typeof VALIDATE_SPEAKER_REQUEST
    | typeof VALIDATE_SPEAKER_SUCCESS
    | typeof VALIDATE_SPEAKER_FAILURE
    | typeof SET_USER_SEARCH_FILTER
    | typeof SET_USER_ROLE_FILTER;
